### ISSUE TITLE
Not included StyleLoss() function in the code

### ISSUE THREAD

**Issue by shonesaji11** [ayu-22/BPPNet-Back-Projected-Pyramid-Network#4]

**Comment by shonesaji11** [comment]
Also while loading the dataset, a mistake has been made while calling  the variable that holds he training images directory, more specifically in the following line,
images_paths_train_gt=glob.glob(path_of_train_gt_images)
where the actual variable name is path_for_train_gt_images.

**Comment by shonesaji11** [comment]
While running the following line of code in class DU_Net
style_loss = StyleLoss()
an error is raised, NameError: name 'StyleLoss' is not defined


Also while loading the dataset, a mistake has been made while calling the variable that holds he training images directory, more specifically in the following line,
images_paths_train_gt=glob.glob(path_of_train_gt_images)
where the actual variable name is path_for_train_gt_images.

**Comment by shonesaji11** [comment]
Also while loading the dataset, a mistake has been made while calling the variable that holds he training images directory, more specifically in the following line,
images_paths_train_gt=glob.glob(path_of_train_gt_images)
where the actual variable name is path_for_train_gt_images.

**Comment by shonesaji11** [comment]
While running the following line of code in class DU_Net
        style_loss = StyleLoss()
an error is raised, NameError: name 'StyleLoss' is not defined

**Comment by shonesaji11** [comment]
Verified using the following command 
grep -nr 'StyleLoss'.
The output is as follows
BPPNet-Back-Projected-Pyramid-Network/Single_Image_Dehazing.ipynb:740:        "        style_loss = StyleLoss()\n",

So I have proved that the function is not defined.

**Comment by ayu-22** [comment]
@shonesaji11 thanks for telling us the error. I corrected the issue. You can check. There was no need for the StyleLoss, so I removed it. And for the "path_for_train_gt_images" I corrected it to the correct name.
