### ISSUE TITLE
The problem with the return value of the process function

### ISSUE THREAD

**Issue by Yaowenzhe** [ayu-22/BPPNet-Back-Projected-Pyramid-Network#8]
In function process, the second return value should logically be DIS_LOSS, but in your code it is the SSIM value. The function calculated DIS_LOSS but did not use it. What is the purpose of this?I tried to change the second return value to DIS_LOSS, but there is a problem that DIS_LOSS will not converge.

**Comment by ayu-22** [comment]
@Yaowenzhe Thanks for telling the error. You are correct, it should be dis_loss, I have done the changes in the file.
